name: Print Secret Value

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Secret
        run: |
          # Retrieve the secret and print its value
          echo "My Secret Value: ${{ secrets.AZURE_CREDENTIALS }}"
